### PR TITLE
Refactoring GWG Leader Updater to Python Class

### PR DESCRIPTION
**Pull request by joefroh**
This is the first of a few coming down the pipe, so if you don't want this change, let me know and I'll abandon the effort.

The end goal here for me is to increase the testability of this code. I won't consider this PR ready for completion until I have a test class against the class to prove its functionality, but essentially what I am aiming for is the following changes:

1. Refactor the .py into a proper class, removing all globals and encapsulating cross cutting concerns (logging)
2. Add a test class so that any additional features/refactors can be done safely
3. remove the Main/Setup functions, and push them into a service execution file and update the service file to reflect that (basically, make a .py for the floating functions, and call that as the entry point for the service executor, removing them from the class file).

This stuff is gonna hopefully be not too rough (the functions themselves are pretty well defined and encapsulated, so once the globals are removed its not bad at all, minimal code churn), but it will be kinda hard for me to test... I'll do my best, but on this one please run a test pass on your side before taking the pull, I noticed I made a small error you had to fix on the last one. Sorry :(

### CODE REVIEW

**Comment by joefroh** [comment]
I will ping this PR when I think its ready for final review, but early feedback is appreciated.

**Comment by KyleBrownCS** [comment]
Only thing I'd like is if you can snake_case functions/methods/variables.

I only needed to fix some gdrive references, everything else is great

**Comment by joefroh** [comment]
Oh true (re snake case). Sorry about that. I'll adhere to the style moving forward 👍

**Comment by KyleBrownCS** [comment]
accidentally closed this PR trying to prep master for a partial set of your changes.

I added some functionality and wanted to manage the conflicts it was going to create for you on remerge. 

Trying to look into how I can reopen this PR

**Comment by joefroh** [comment]
I still have the branch (took some time off. Sorry for going awol). Worst case I can just open a new one and merge down your changes.

Joey

________________________________

**Comment by joefroh** [comment]
My read is you can't reopen a closed PR if its been merged (this one has). I'll clean up after all the merging and open a new PR for writing the tests. It was basically the only thing left anyway

**Pull request merged**
